# Generated by Django 5.0.1 on 2024-01-05 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pin_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
